  name: set-up-env
  description: 设置环境变量
  inputs:
    docker:
      description: 是否是Docker项目
      default: false
    docker-registry:
      default: docker-registry
      required: true
  runs:
    using: composite
    steps:
        - name: 设置环境变量
          shell: bash
          run: |
            
            parse_env() {
              if [[ "${{ github.event_name }}" == "release" ]]; then
                if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
                  env=qa
                else
                  env=prod
                fi
              else
                env=dev
              fi
            }
            
            parse_env
            
            sha=${{ github.sha }}
            tag="v$GITHUB_RUN_NUMBER.$GITHUB_REF_NAME.$GITHUB_ACTOR."${sha: 0:7}"."$(date "+%Y.%m.%d.%H.%M.%S")
            # 设置环境变量
            echo "TAG=$tag" >> $GITHUB_ENV
            # Get the full repository name
            full_repo_name=$GITHUB_REPOSITORY

            # Separate owner and repository name
            owner=$(echo "$full_repo_name" | cut -d '/' -f 1)
            repo_name=$(echo "$full_repo_name" | cut -d '/' -f 2)
            
            if [[ "${{ inputs.docker }}" == "true" ]]; then
              echo "Docker 项目"
            else
              echo "非Docker 项目"
            fi

            # Set environment variables
            echo "ENV=$ENV" >> $GITHUB_ENV
            echo "OWNER=$owner" >> $GITHUB_ENV
            echo "REPO_NAME=$repo_name" >> $GITHUB_ENV
            echo "APP_NAME=$env-$repo_name" >> $GITHUB_ENV
            echo "TAG=$tag" >> $GITHUB_ENV
        - name: 打印环境变量
          shell: bash
          run: |
            echo "环境：ENV=$env"
            echo "仓库所有者：OWNER=$owner"
            echo "仓库名称：REPO_NAME=$repo_name"
            echo "应用名称（带环境）:APP_NAME=$env-$repo_name"
            echo "运行次数：GITHUB_RUN_NUMBER=$GITHUB_RUN_NUMBER"
            echo "引用名称：GITHUB_REF_NAME=$GITHUB_REF_NAME"
            echo "标签：TAG=$TAG"
